print("Welcome to the tip calculator!\n \n")
bill_total = input("What was the total of the bill?\n$")
print("\n")
diner_total = input("How many diners do you wish to split the  bill between?\n")
print("\n")
tip_percent = input("What percentage would you like to tip - 10, 12 or 15 percent? \n")
print("\n")
tip=( float(bill_total) / 100) * int(tip_percent)
bill_and_tip = float(tip) + float(bill_total)
price_per_diner = float(bill_and_tip) / int(diner_total)
print('$', price_per_diner)
